server:
  port: 8092

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.228.188

  rabbitmq:
    host: 192.168.228.188
    virtual-host: /huigege
    username: huigege
    password: huigege

auth:
  jwt:
    publicKeyPath: E:\developWorkspace\workspace_idea\tmp\rsa.pub
    cookieName: GMALL_TOKEN


