server:
  port: 8888
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes: #\u8DEF\u7531\uFF0C\u914D\u7F6E\u4E3A\u4E00\u4E2Alist\u96C6\u5408 List<RouteDefinition>\uFF0C\u6BCF\u4E2A\u5143\u7D20\u8981\u4EE5 - \u5F00\u5934
        - id: pms-route #\u8DEF\u7531\u7684\u552F\u4E00\u6807\u5FD7\uFF0C\u901A\u5E38\u53D6\u670D\u52A1\u540D
          uri: lb://pms-service #\u5FAE\u670D\u52A1\u7684\u8BBF\u95EE\u8DEF\u5F84\uFF0Clb\u652F\u6301\u8D1F\u8F7D\u5747\u8861
          predicates: #\u65AD\u8A00(\u5224\u65AD\u8BF7\u6C42\u8DEF\u5F84\u8BE5\u8FDB\u5165\u54EA\u4E2A\u5FAE\u670D\u52A1\uFF0C\u8BE5\u4E0D\u8BE5\u8FDB\u5165\u8FD9\u4E2A\u5FAE\u670D\u52A1)
            - Path=/pms/** #\u5224\u65AD\u8BF7\u6C42\u8DEF\u5F84\u662F\u5426\u7B26\u5408,/pms/\u7528\u6765\u533A\u5206\u5FAE\u670D\u52A1\u7684
         #filters:   \u91CD\u5199\u8DEF\u5F84\uFF1A\u4EE5\u9017\u53F7\u548C\u7A7A\u683C\u5206\u5272
          # - RewritePath=/pms/(?<segment>.*), /$\{segment} \u9017\u53F7\u524D\u91CD\u5199\u524D\uFF0C\u9017\u53F7\u540E\u91CD\u5199\u540E
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

